"""Gyro: make Steam Input read the Ally's gyro axes the right way.

Ported from the Gyro Fix of Ally Fix (https://github.com/lonsdaleite/Ally-Fix, MIT).

Steam identifies InputPlumber's `deck-uhid` target by product id. For the Ally id it treats the
controller as a handheld and tilts the IMU frame, and its two gyro code paths (modern gyro modes
and the legacy Camera action of Valve's Source layouts) apply that tilt differently. Modes:

- simple: stock config with the mount-matrix y row negated. Modern modes right; Source layouts keep
  Yaw and Roll swapped.
- complex: `gyro_force_handheld_orientation 2` in Steam's steam_dev.cfg plus the y/z rows swapped.
  Everything right; Steam must restart when the line is added or removed.
- deck: composite device renamed so InputPlumber emulates the generic id with the stock matrix.
  Everything right, but layouts saved for the ROG Ally no longer apply.

The override in /etc/inputplumber/devices.d is generated from the installed stock file and stamped
with its hash, so an InputPlumber update is detected (stale) and the override regenerated.
Overrides written by Ally Fix are taken over.
"""
from __future__ import annotations

import asyncio
import hashlib
import os
import re
import time
from typing import Any, Dict, List, Optional, Tuple

from .. import dbus, device, steam
from ..constants import INPUTPLUMBER_BUS
from ..log import logger
from ..module import Module
from ..util import run

STOCK = "/usr/share/inputplumber/devices/50-rog_xbox_ally.yaml"
OVERRIDE_DIR = "/etc/inputplumber/devices.d"
OVERRIDE = os.path.join(OVERRIDE_DIR, "50-rog_xbox_ally.yaml")
MARKER = "managed-by: ally-companion"
FOREIGN_MANAGED = ("managed-by: ally-fix",)  # predecessors whose overrides are taken over
TARGETS_CACHE_S = 10.0

MODES = ("simple", "complex", "deck")
DECK_NAME = "ASUS ROG Xbox Ally (Deck Emulation)"  # matches no arm in InputPlumber's PID table

CONVAR = "gyro_force_handheld_orientation"
CONVAR_LINE = f"{CONVAR} 2"
COMPOSITE_IFACE = "org.shadowblip.Input.CompositeDevice"

_ROW_Y = re.compile(r"^([ \t]*)y:[ \t]*\[\s*0\s*,\s*-1\s*,\s*0\s*\][ \t]*$", re.M)
_ROW_Z = re.compile(r"^([ \t]*)z:[ \t]*\[\s*0\s*,\s*0\s*,\s*-1\s*\][ \t]*$", re.M)
_NAME = re.compile(r"^name:[ \t]*ASUS ROG Xbox Ally[ \t]*$", re.M)
_HASH_LINE = re.compile(r"^# stock-sha256:\s*([0-9a-f]{64})\s*$", re.M)

_MODE_NOTE = {
    "simple": "the IMU mount-matrix y row is negated (Simple mode)",
    "complex": "the IMU mount-matrix y and z rows are swapped (Complex mode, with\n"
               "# gyro_force_handheld_orientation 2 in Steam's steam_dev.cfg)",
    "deck": "the composite device is renamed so InputPlumber emulates the generic\n"
            "# Steam Controller product id (Deck Emulation mode)",
}


def steam_cfg() -> str:
    return os.path.join(steam.steam_dir(), "steam_dev.cfg")


def sha256(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def patch(stock_text: str, mode: str) -> str:
    """Stock config with the one change a mode needs; raises when the stock file no longer has
    the lines to patch (upstream changed)."""
    if mode == "simple":
        text, n = _ROW_Y.subn(r"\1y: [0, 1, 0]", stock_text, count=1)
        ok = n == 1
    elif mode == "complex":
        text, n1 = _ROW_Y.subn(r"\1y: [0, 0, -1]", stock_text, count=1)
        text, n2 = _ROW_Z.subn(r"\1z: [0, -1, 0]", text, count=1)
        ok = n1 == 1 and n2 == 1
    elif mode == "deck":
        text, n = _NAME.subn(f"name: {DECK_NAME}", stock_text, count=1)
        ok = n == 1
    else:
        raise ValueError(f"unknown gyro mode {mode!r}")
    if not ok:
        raise RuntimeError("stock config has no line to patch for this mode; InputPlumber changed")
    return text


def render(stock_text: str, stock_hash: str, mode: str) -> str:
    header = (
        f"# {MARKER}\n"
        f"# stock-sha256: {stock_hash}\n"
        f"# mode: {mode}\n"
        "# Generated by the Ally Companion Decky plugin from the stock InputPlumber config.\n"
        f"# Only change: {_MODE_NOTE[mode]}. Delete this file to return to stock.\n\n"
    )
    return header + patch(stock_text, mode)


def body(text: str) -> str:
    """Config text without comments and blank lines."""
    return "\n".join(l.rstrip() for l in text.splitlines() if l.strip() and not l.lstrip().startswith("#"))


def read_text(path: str) -> Optional[str]:
    try:
        with open(path, "r", encoding="utf-8", newline="") as f:
            return f.read()
    except OSError:
        return None
    except ValueError:
        return "�"  # not UTF-8: a foreign file


def is_convar_line(line: str) -> bool:
    return line.split() == [CONVAR, "2"]


def edit_steam_cfg(text: Optional[str], present: bool, prev: str) -> Tuple[Optional[str], str]:
    """New steam_dev.cfg content (None: delete the file) and the line to restore later.

    Other lines stay byte for byte, line endings included. A different value someone else set is
    replaced in place and put back when our line goes."""
    cur = (text or "").splitlines(keepends=True)
    ours = [i for i, l in enumerate(cur) if is_convar_line(l)]
    theirs = [i for i, l in enumerate(cur) if l.split()[:1] == [CONVAR] and not is_convar_line(l)]

    def eol(line: str) -> str:
        return "\r\n" if line.endswith("\r\n") else "\n"

    if present:
        if ours:
            return text, prev
        new = list(cur)
        if theirs:
            prev = cur[theirs[0]].rstrip("\r\n")
            new[theirs[0]] = CONVAR_LINE + eol(cur[theirs[0]])
            new = [l for i, l in enumerate(new) if i not in theirs[1:]]
        else:
            prev = ""
            nl = next((eol(l) for l in new if l.endswith("\n")), "\n")
            if new and not new[-1].endswith(("\n", "\r")):
                new[-1] += nl
            new.append(CONVAR_LINE + nl)
    else:
        if not ours:
            return text, ""
        new = list(cur)
        drop = ours
        if prev and not theirs:
            new[ours[0]] = prev + eol(cur[ours[0]])
            drop = ours[1:]
        new = [l for i, l in enumerate(new) if i not in drop]
        prev = ""
    out = "".join(new)
    return (out if out.strip() else None), prev


class Gyro(Module):
    id = "gyro"
    title = "Gyro"
    toggle = True
    defaults = {"enabled": False, "mode": "simple", "steamCfgPrev": ""}

    def __init__(self) -> None:
        super().__init__()
        self._targets: Tuple[float, List[str]] = (0.0, [])

    @property
    def mode(self) -> str:
        m = self.cfg.get("mode", "simple")
        return m if m in MODES else "simple"

    def set_options(self, opts: Dict[str, Any]) -> bool:
        mode = opts.get("mode")
        if mode in MODES and mode != self.cfg.get("mode"):
            self.update_cfg({"mode": mode})
            return True
        return False

    # ------------------------------------------------------------- inspection
    def override_state(self) -> str:
        """absent | foreign | stale | mismatch | current"""
        text = read_text(OVERRIDE)
        if text is None:
            return "absent"
        managed = MARKER in text or any(m in text for m in FOREIGN_MANAGED)
        if not os.path.exists(STOCK):
            return "stale" if managed else "foreign"
        if not managed:
            stock_text = read_text(STOCK) or ""
            for m in MODES:
                try:
                    if body(text) == body(patch(stock_text, m)):
                        return "mismatch"  # a hand-made copy of one of our modes: safe to overwrite
                except RuntimeError:
                    pass
            return "foreign"
        found = _HASH_LINE.search(text)
        if not found or found.group(1) != sha256(STOCK):
            return "stale"
        try:
            expected = render(read_text(STOCK) or "", found.group(1), self.mode)
        except RuntimeError:
            return "mismatch"
        return "current" if text == expected else "mismatch"

    def steam_cfg_has_convar(self) -> bool:
        text = read_text(steam_cfg()) or ""
        return any(is_convar_line(l) for l in text.splitlines())

    # ------------------------------------------------------------- module interface
    def supported(self) -> Tuple[bool, str]:
        if not device.is_xbox_ally():
            return False, f"needs a ROG Xbox Ally (board {device.board() or 'unknown'})"
        if not os.path.exists(STOCK):
            return False, "InputPlumber config for the ROG Xbox Ally not found"
        return True, ""

    def is_applied(self) -> bool:
        return self.override_state() == "current" and self.steam_cfg_has_convar() == (self.mode == "complex")

    def refine(self, state: str, message: str, details: Dict[str, Any]) -> Tuple[str, str]:
        if state in ("applied", "not_applied"):
            ov = details.get("override")
            if ov == "stale":
                return "stale", "InputPlumber was updated; the override needs to be regenerated"
            if ov == "foreign":
                return "error", f"{OVERRIDE} exists but was not created by this plugin"
        return state, message

    async def apply(self) -> None:
        async with self._lock:
            await self._apply()

    async def revert(self) -> None:
        async with self._lock:
            await self._revert()

    async def _apply(self) -> None:
        state = self.override_state()
        if state == "foreign":
            raise RuntimeError(f"{OVERRIDE} is not managed by this plugin; remove it manually first")
        stock_text = read_text(STOCK) or ""
        try:
            text = render(stock_text, sha256(STOCK), self.mode)
        except RuntimeError:
            if state == "stale":
                os.remove(OVERRIDE)  # never leave an outdated full copy shadowing a newer stock config
                await self._restart_inputplumber()
            raise
        if read_text(OVERRIDE) != text:
            os.makedirs(OVERRIDE_DIR, mode=0o755, exist_ok=True)
            tmp = OVERRIDE + ".tmp"
            with open(tmp, "w", encoding="utf-8") as f:
                f.write(text)
            os.chmod(tmp, 0o644)
            os.replace(tmp, OVERRIDE)
            logger.info("[gyro] override written (mode %s)", self.mode)
            await self._restart_inputplumber()
        self._set_convar(self.mode == "complex")

    async def _revert(self) -> None:
        state = self.override_state()
        try:
            if state not in ("foreign", "absent"):
                os.remove(OVERRIDE)
                logger.info("[gyro] override removed")
                await self._restart_inputplumber()
        finally:
            self._set_convar(False)
        if state == "foreign":
            raise RuntimeError(f"{OVERRIDE} is not managed by this plugin; not removing it")

    def _set_convar(self, present: bool) -> None:
        path = steam_cfg()
        text = read_text(path)
        if text == "�":
            raise RuntimeError(f"{path} is not UTF-8; not touching it")
        new, prev = edit_steam_cfg(text, present, str(self.cfg.get("steamCfgPrev") or ""))
        self.update_cfg({"steamCfgPrev": prev})
        if new == text:
            return
        if not os.path.isdir(os.path.dirname(path)):
            raise RuntimeError(f"Steam directory not found: {os.path.dirname(path)}")
        if new is None:
            os.remove(path)
        else:
            st = os.stat(path) if text is not None else None
            tmp = path + ".tmp"
            with open(tmp, "w", encoding="utf-8", newline="") as f:
                f.write(new)
            os.chmod(tmp, st.st_mode & 0o777 if st else 0o644)
            if st:
                os.chown(tmp, st.st_uid, st.st_gid)
            else:
                steam.chown_user(tmp)
            os.replace(tmp, path)
        logger.info("[gyro] %s %s in steam_dev.cfg", "wrote" if present else "removed", CONVAR)

    async def _restart_inputplumber(self) -> None:
        r = await asyncio.to_thread(run, ["systemctl", "restart", "inputplumber"], 30)
        if not r.ok:
            raise RuntimeError(f"systemctl restart inputplumber failed: {(r.err or r.out).strip()}")
        logger.info("[gyro] inputplumber restarted")

    def _target_types(self) -> List[str]:
        try:
            paths = [p for p in dbus.tree(INPUTPLUMBER_BUS) if re.fullmatch(r"/org/shadowblip/InputPlumber/CompositeDevice\d+", p)]
        except dbus.DBusError:
            return []
        composite = None
        for p in paths:
            if "ally" in str(dbus.try_get_property(INPUTPLUMBER_BUS, p, COMPOSITE_IFACE, "Name") or "").lower():
                composite = p
                break
        composite = composite or (paths[0] if paths else None)
        if composite is None:
            return []
        targets = dbus.try_get_property(INPUTPLUMBER_BUS, composite, COMPOSITE_IFACE, "TargetDevices") or []
        types = []
        for t in targets:
            v = dbus.try_get_property(INPUTPLUMBER_BUS, t, "org.shadowblip.Input.Target", "DeviceType")
            if v:
                types.append(str(v))
        return types

    def details(self) -> Dict[str, Any]:
        now = time.monotonic()
        ts, targets = self._targets
        if now - ts >= TARGETS_CACHE_S:
            targets = self._target_types()
            self._targets = (now, targets)
        return {"mode": self.mode, "override": self.override_state(), "steamCfgPresent": self.steam_cfg_has_convar(),
                "targets": targets, "deckUhid": "deck-uhid" in targets}
