export const t = {
  title: "Ally Companion",
  allSettings: "All settings",
  unsupported: "Unsupported device",
  backendError: "Backend not reachable",
  retry: "Retry",
  allGood: "Everything in order",
  staleUi: "Updated: press B and reopen Ally Companion",
  updateTo: (v: string) => `Install update v${v}`,
  updateFailed: "Update failed",

  overview: "Overview",
  audio: "Audio",
  controller: "Controller",
  lighting: "Lighting",
  power: "Power & battery",
  profiles: "Game profiles",
  news: "News",
  system: "System",

  device: "Device",
  model: "Model",
  bios: "BIOS",
  mcu: "Controller firmware",
  notReported: "not reported by the driver",
  os: "Operating system",
  kernel: "Kernel",
  services: "System interfaces",
  inputplumber: "InputPlumber",
  steamosManager: "steamos-manager",
  allyDriver: "Controller driver (hid_asus_ally)",
  ledRing: "Joystick LED rings",
  armoury: "ASUS firmware attributes (asus-armoury)",
  available: "available",
  missing: "missing",
  notRunning: "not running",
  modules: "Modules",
  noModules: "No modules.",
  notSupported: "Not supported",

  version: "Version",
  checkUpdate: "Check for updates",
  upToDate: "Up to date",
  diagnostics: "Diagnostics",
  createReport: "Create report",
  reportSaved: "Also saved to ~/homebrew/logs/Ally Companion/diagnostics.txt",
  source: "Source code",
};
